# Generated by Django 4.2.4 on 2023-08-13 01:32

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0005_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('creation_date', models.DateField(default=datetime.date(2023, 8, 12))),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('creation_date', models.DateField(default=datetime.date(2023, 8, 12))),
                ('mark_relevant', models.BooleanField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('discussion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forums.discussion')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('creation_date', models.DateField(default=datetime.date(2023, 8, 12))),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='forum_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forums.forum'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project'),
        ),
    ]
