# Generated by Django 4.2.4 on 2023-08-13 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='forum',
            name='creation_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
