# Generated by Django 4.2.4 on 2023-10-05 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0002_alter_discussion_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='state',
            field=models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='state',
            field=models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open'),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
