# Generated by Django 4.2.4 on 2023-10-19 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0008_alter_project_options'),
        ('Forums', '0003_alter_discussion_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'Discusión'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': 'Foro'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mensaje'},
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/ForumMessage/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forums.forum', verbose_name='Foro'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='state',
            field=models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='state',
            field=models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='message',
            name='discussion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forums.discussion', verbose_name='Discusión'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mark_relevant',
            field=models.BooleanField(verbose_name='Marcar como Relevante'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
