# Generated by Django 4.2.4 on 2023-08-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ident_number',
            field=models.CharField(max_length=50, verbose_name='Número de Identificación'),
        ),
    ]
