# Generated by Django 4.2.4 on 2023-08-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
