# Generated by Django 4.2.4 on 2023-08-13 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_alter_project_title'),
        ('Knowledge', '0002_alter_knowledge_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project'),
        ),
    ]
