# Generated by Django 4.2.4 on 2023-08-13 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge', '0004_rename_knowledge_id_knowledgestep_knowledge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='creation_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='knowledgestep',
            name='creation_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
