# Generated by Django 4.2.4 on 2023-10-05 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge', '0005_alter_knowledge_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='partner_ids',
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='state',
            field=models.CharField(choices=[('new', 'Nuevo'), ('for_approval', 'Por Aprobar'), ('approved', 'Aprobado'), ('archived', 'Archivado')], default='new'),
        ),
        migrations.AlterField(
            model_name='knowledgestep',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
