# Generated by Django 4.2.4 on 2023-10-18 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0008_alter_project_options'),
        ('Knowledge', '0006_remove_knowledge_partner_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name': 'Conocimiento'},
        ),
        migrations.AlterModelOptions(
            name='knowledgetype',
            options={'verbose_name': 'Tipo de Conocimiento'},
        ),
        migrations.AddField(
            model_name='knowledgestep',
            name='image',
            field=models.ImageField(null=True, upload_to='../Knowledge/uploads/KnowledgeSteps/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='note',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='state',
            field=models.CharField(choices=[('new', 'Nuevo'), ('for_approval', 'Por Aprobar'), ('approved', 'Aprobado'), ('archived', 'Archivado')], default='new', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Knowledge.knowledgetype', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='knowledgestep',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='knowledgestep',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='knowledgestep',
            name='knowledge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knowledge.knowledge', verbose_name='Conocimiento'),
        ),
        migrations.AlterField(
            model_name='knowledgestep',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
