# Generated by Django 4.2.4 on 2023-10-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge', '0008_alter_knowledgestep_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgestep',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/KnowledgeSteps/', verbose_name='Imagen'),
        ),
    ]
