# Generated by Django 4.2.4 on 2023-08-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='draft'),
        ),
    ]
