# Generated by Django 4.2.4 on 2023-08-13 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
