# Generated by Django 4.2.4 on 2023-10-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_alter_project_created_by_alter_project_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto'},
        ),
    ]
